### ISSUE TITLE
When I use this module Framer cloud won't load the project's images

### ISSUE THREAD

**Issue by blaineb** [marckrenn/framer-QueryInterface#1]
I'm not sure if it's even in your power to fix, but if so that would be amazing.

**Comment by marckrenn** [comment]
Hey @blaineb, thanks for reporting this issue!

This is a problem caused by framer.cloud (rather aggressively) trying to shorten sharing URLs by removing the version suffix (eg. the `/1/` part of https://framer.cloud/gpuDz/1/).

While I won't be able to fix this behaviour directly for obvious reasons, I've found this quick and easy workaround here:


Just put a slash `/` in front of the query like this:

> https://framer.cloud/gpuDz/?bgColor=02b72a

instead of using the auto-generated

> https://framer.cloud/gpuDz?bgColor=02b72a


With this modification, your images should load fine.

Thanks for using this module 👍

**Comment by blaineb** [comment]
Sweeeeeet.  You're the man.  Thanks for making the module and for the fix.
